version: '3.7'
services:
  api:
    build:
      context: .
      target: development
    command: cargo watch -x run
    environment:
      - RUST_LOG=info
    volumes:
      - ./api/src:/app/src
      - ./api/Cargo.toml:/app/Cargo.toml
    ports:
      - "8000:8000"
